services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_URL=https://worldpass-beta.heptapusgroup.com
      - IPFS_API_URL=http://ipfs:5001
      - IPFS_GATEWAY=http://ipfs:8080/ipfs
    env_file:
       - .env
    volumes:
      - ./data:/data

    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: web/Dockerfile
    depends_on:
      - backend
    restart: unless-stopped

  caddy:
    image: caddy:2.8
    depends_on:
      - backend
      - frontend
      - ipfs
    ports:
      - "80:80"
      # DNS + HTTPS gelince açılacak:
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./data/caddy:/data   
      - ./data/config:/config
    restart: unless-stopped

  ipfs:
    image: ipfs/kubo:latest
    container_name: ipfs
    ports:
      - "5001:5001"   # API
      - "8080:8080"   # Gateway
      - "4001:4001"   # Swarm
    volumes:
      - ./data/ipfs:/data/ipfs
      - ./data/ipfs-staging:/export
    environment:
      - IPFS_PROFILE=server
    restart: unless-stopped

